# Generated by Django 4.2 on 2023-05-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=90),
        ),
    ]
